### ISSUE TITLE
Display Web Feature Service

### ISSUE THREAD

**Issue by JoeChen7702** [interactive-instruments/ldproxy#756] opened 2022-11-02 03:45 UTC
### ldproxy Version

3.2.4

### Current Behavior

Hi there, I try to bind Web Feature Service from GeoServer on Ldproxy, and get "HTTP Error 400: Bad Request Could not parse GML: null" when I open the service on Google Chrome and wonder if there is any suggestion to solve this problem. For more detail please check the attachment.
![image](https://user-images.githubusercontent.com/75831881/199388724-efde38c5-ad4a-44da-a02a-759b68b5865d.png)
![image](https://user-images.githubusercontent.com/75831881/199388745-b5d3c7d2-213c-4ce4-afa5-66682e700999.png)
[wfs.zip](https://github.com/interactive-instruments/ldproxy/files/9915717/wfs.zip)

### Expected Behavior

Able display Web Feature Service from GeoServer on Ldproxy.

### Steps to Reproduce

Step 1. Add Web Feature Service form GeoServer on Ldproxy.
Step 2. Open Service from Ldproxy.

**Comment by cportele** [comment] 2022-11-02 08:02
Without access to a WFS instance with that behavior, this is impossible to analyze. I can see that it is a WFS 1.0 instance, maybe this is related to using this very old version.

**Comment by JoeChen7702** [comment] 2022-11-02 09:12
Hi [cportele](https://github.com/cportele)

 I did try WFS 2.0 instance, which you can find as the attachment, but still get the same issue, any suggestion?

[poi.zip](https://github.com/interactive-instruments/ldproxy/files/9918770/poi.zip)
![image_2022_11_02T08_51_18_036Z](https://user-images.githubusercontent.com/75831881/199450373-bc741330-157c-409e-99fd-5deaf897412a.png)

**Comment by azahnen** [comment] 2022-11-07 09:52
To really be able to analyze the issue we need a public WFS that we can access. If that is not possible, there might be some hints in the log. Could you set the log level to debug and paste the log for the request?

**Comment by JoeChen7702** [comment] 2022-11-08 08:18
Hi [azahnen](https://github.com/azahnen),

Unfortunately, I am not able to provide a public WFS. Instead, I have attached the log here. 

[756 Display Web Feature Servic Log.zip](https://github.com/interactive-instruments/ldproxy/files/9959042/756.Display.Web.Feature.Servic.Log.zip)

**Comment by azahnen** [comment] 2022-11-08 13:11
Sorry, but the log snippet is too short to be helpful.
Let's try this:

1. go back to zero and start with a fresh data directory
2. enable debug logging
3. add a new service using WFS 2.0
4. open the service

Then:

1. Attach the full log
2. Attach the response to the GetCapabilities request found in the log
3. Attach the response to the GetFeature request found in the log

**Comment by JoeChen7702** [comment] 2022-11-09 02:05
Hi [azahnen](https://github.com/azahnen),

 I have attached the log files you needed as below: 
[Fulllog.zip](https://github.com/interactive-instruments/ldproxy/files/9966652/Fulllog.zip)
[GetCapabilities.zip](https://github.com/interactive-instruments/ldproxy/files/9966653/GetCapabilities.zip)
[GetFeature.zip](https://github.com/interactive-instruments/ldproxy/files/9966654/GetFeature.zip)

Additionally, could you tell where I can find a GML parser function in the source code, thank you.

**Comment by JoeChen7702** [comment] 2022-11-11 10:59
Hi [azahnen](https://github.com/azahnen),

I found that the ldprxoy application will interrupt at createFeature process, I wonder if you can tell me where this program is in the source code, so then I can help to look at this error, thank you.

![image_2022_11_11T09_33_53_225Z](https://user-images.githubusercontent.com/75831881/201326505-60eda047-352c-45ca-afa0-fe7c43e75b7c.png)
[ldproxyfulllog.zip](https://github.com/interactive-instruments/ldproxy/files/9989641/ldproxyfulllog.zip)

**Comment by azahnen** [comment] 2022-11-15 17:36
Sorry, I guess I haven't made myself clear enough. What I need is the response to these requests:

- http://140.134.48.91:8080/geoserver/HongKong/ows?REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0
- http://140.134.48.91:8080/geoserver/HongKong/ows?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&COUNT=10&TYPENAMES=HongKong%3Atest7&SRSNAME=EPSG%3A2326&NAMESPACES=xmlns%28xsi%2Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema-instance%29%2Cxmlns%28%2Chttp%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%29%2Cxmlns%28ows%2Chttp%3A%2F%2Fwww.opengis.net%2Fows%2F1.1%29%2Cxmlns%28gml%2Chttp%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%29%2Cxmlns%28fes%2Chttp%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%29%2Cxmlns%28xlink%2Chttp%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%29%2Cxmlns%28xs%2Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%29%2Cxmlns%28xml%2Chttp%3A%2F%2Fwww.w3.org%2FXML%2F1998%2Fnamespace%29%2Cxmlns%28HongKong%2CHongKong%29

**Comment by JoeChen7702** [comment] 2022-11-16 01:35
I have attached the log files you needed as below:

[geoserver-GetCapabilities.zip](https://github.com/interactive-instruments/ldproxy/files/10017342/geoserver-GetCapabilities.zip)
[test7.zip](https://github.com/interactive-instruments/ldproxy/files/10017343/test7.zip)

**Comment by cportele** [comment] 2022-11-16 08:21
The configuration of test7 must be incorrect. The CRS is given as EPSG:2326, which is 2D. However, the coordinates are 3D and srsDimension is set to 4.

**Comment by JoeChen7702** [comment] 2022-11-21 02:49
Hi cportele and azahnen,

Regarding huge amount of geodata, some of which includes z-dimenesion. We want to find out if there is any way to avoid this issue.

We have come up with 2 approaches and please suggest which is more recommended,

1. If I want to modify the ldproxy application to deal with this issue, should I start the modification at xtraplatform which is included when the ldproxy doing the WFS parser.
2. Bulid a verfication application to check if these is z-dimenesion data in the wfs before doing the "add Services" process in ldproxy.

![image](https://user-images.githubusercontent.com/75831881/202952757-ab01b73d-7820-4def-be71-d2aec759e2f6.png)

**Comment by JoeChen7702** [comment] 2022-11-22 01:10
Hi https://github.com/cportele,

I have another question about your previous comment below:

> The configuration of test7 must be incorrect. The CRS is given as EPSG:2326, which is 2D. However, the coordinates are 3D and srsDimension is set to 4.

I wonder if the LDproxy can accept  Web Feature Service with 3D data. If so, do you have any example, thank you!

**Comment by JoeChen7702** [comment] 2022-11-22 02:53
Hi cportele,

I have another question about your previous comment below:

The configuration of test7 must be incorrect. The CRS is given as EPSG:2326, which is 2D. However, the coordinates are 3D and srsDimension is set to 4.

I wonder if the LDproxy can accept Web Feature Service with 3D data?  If so, do you have any example or suggested configuration of the data in order make it works with LDProxy, thank you!

**Comment by azahnen** [comment] 2022-11-24 13:16
ldproxy can handle 3d data perfectly fine. 
The problem is that your WFS returns `srsDimension="4"`, correct would be `srsDimension="3"`. So you have to fix the configuration of GeoServer or whatever you are using for the WFS.

I am closing this issue, if you have any more questions about ldproxy, please use [Discussions](https://github.com/interactive-instruments/ldproxy/discussions).

**Closed by azahnen** 2022-11-24 13:16 UTC
Labels: question
