### ISSUE TITLE
changing properties on the admin section not visible publicly

### ISSUE THREAD

**Issue by pvgenuchten** [interactive-instruments/ldproxy#46] opened 2017-06-12 11:21 UTC
when changing a value on feature-attribute-properties, it seems to be stored on the system, but i don’t see any changes in the exported json-ld structure, i need to click a save/apply button somewhere or restart the service?

**Comment by azahnen** [comment] 2017-11-04 14:39
duplicate of #74

**Closed by azahnen** 2017-11-04 14:39 UTC
