### ISSUE TITLE
Changing admin password gets stuck

### ISSUE THREAD

**Issue by rockliffelewis** [interactive-instruments/ldproxy#695] opened 2022-07-08 01:36 UTC
### ldproxy Version

v3.2.4

### Current Behavior

When ldproxy is started for the first time, the admin password is required to be changed.

Upon completing the change password form, it appears to get stuck in a loop, even if you log out and back in it still asks for the password to be changed.

If you delete the cookie, and log in again then it continues as expected

### Expected Behavior

Once you change the admin password, it redirects either to log in again or to the manager home page

### Steps to Reproduce

Start fresh ldproxy
log into the manager console with admin
change the admin password as requested
click submit

**Comment by azahnen** [comment] 2022-10-17 07:21
This is a duplicate of #687, it should be fixed in `iide/ldproxy:next`.

**Closed by azahnen** 2022-10-17 07:21 UTC
Labels: bug, duplicate
