### ISSUE TITLE
Display Web Feature Service With ZIndex Property

### ISSUE THREAD

**Issue by JoeChen7702** [interactive-instruments/ldproxy#771] opened 2022-11-07 08:06 UTC
### ldproxy Version

3.2.4

### Current Behavior

Hi [cportele](https://github.com/cportele), I get an error "HTTP Error 400: Bad Request. Could not parse GML: Index 1014 out of bounds for length 1014" when binding Web Feature Service includes ZIndex Property. Do you have any suggestions for this ?
![Error Message](https://user-images.githubusercontent.com/75831881/200257725-fdb7dbf3-3acb-4a65-b168-9066844e0ca5.png)
![GeoData Content](https://user-images.githubusercontent.com/75831881/200257731-ee0508f2-465b-451a-a53c-b3dcaedfdc33.png)

### Expected Behavior

Able display Web Feature Service from GeoServer on Ldproxy.

### Steps to Reproduce

Step 1. Add Web Feature Service form GeoServer on Ldproxy.
Step 2. Open Service from Ldproxy.

**Comment by azahnen** [comment] 2022-11-07 09:57
Again, to really be able to analyze the issue we need a public WFS that we can access. If that is not possible, there might be some hints in the log. Could you set the log level to debug and paste the log for the request?

Additionally, the snippet does not contain the parent MultiSurface. What are `srsName` and `srsDimension` set to?

**Comment by JoeChen7702** [comment] 2022-11-08 08:27
Hi [azahnen](https://github.com/azahnen),

There is no srsName and srsDimension set in feature collection from this WFS.
Also, I have attached the log file as below:
[771 Display Web Feature Service With ZIndex Property.zip](https://github.com/interactive-instruments/ldproxy/files/9959140/771.Display.Web.Feature.Service.With.ZIndex.Property.zip)
Let me know if you need any further information, thank you.

**Comment by azahnen** [comment] 2022-11-16 09:20
I am pretty sure this is a duplicate of #756, so I am closing this. To be useable in ldproxy, the WFS has to provide correct values for `srsName` and `srsDimension`.

**Closed by azahnen** 2022-11-16 09:20 UTC
Labels: question
